const BookmarksActionTypes = {
  ACTIVE_CATEGORY: 'ACTIVE_CATEGORY',
  ROMOVE_ACTIVE_BOOKMARK: 'ROMOVE_ACTIVE_BOOKMARK',
  ADD_BOOKMARK: 'ADD_BOOKMARK',
  DELETE_BOOKMARK: 'DELETE_BOOKMARK'
}

export default BookmarksActionTypes;