
const UserActionTypes = {
  "LOGIN_START": 'LOGIN_START',
  "LOGIN_SUCCESS": 'LOGIN_SUCCESS',
  "LOGIN_FAILURE": 'LOGIN_FAILURE',
  "SIGNUP_START": "SIGNUP_START",
  "SIGNUP_SUCCESS": "SIGNUP_SUCCESS",
  "SIGNUP_FAILURE": "SIGNUP_FAILURE",
  "CHECK_LOGIN": "CHECK_LOGIN",
  "LOGOUT": 'LOGOUT'
}

export default UserActionTypes;